<Project Sdk="Microsoft.NET.Sdk.Worker"><ItemGroup><ProjectReference Include="../Sidecil.Tickets.Infrastructure/Sidecil.Tickets.Infrastructure.csproj"/><PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.12"/></ItemGroup><ItemGroup Condition="'$(MailBundle)' == 'true'"><Content Update="appsettings*.json" CopyToPublishDirectory="Never" /><None Update="appsettings*.json" CopyToPublishDirectory="Never" /></ItemGroup></Project>